### ISSUE TITLE
Support latest version and/or branches

### ISSUE THREAD

**Issue by bbugh** [fabasoad/setup-mint-action#32]
Hi! 👋 Thanks for doing this, I was searching to see if anyone else had done it before doing it myself, and lo and behold, you already did!

**Is your feature request related to a problem? Please describe.**

I am using the latest version of mint on master for testing and development (and line comments). I'd like to be able to build with that.

**Describe the solution you'd like**

Ideally, the version could be `latest` or `master`, or better yet a branch name, and it would download and use that. GitHub will create archives out of branches, like `https://github.com/mint-lang/mint/archive/refs/heads/master.zip` or `https://github.com/mint-lang/mint/archive/refs/heads/some-branch.zip` that can be downloaded. It looks like `@actions/tool-cache` supports this. What do you think?

**Describe alternatives you've considered**

Doing it manually... boooo

**Comment by fabasoad** [comment]
Hi @bbugh! Thanks for your interest to this project :)
Hm.. I understood your need but I'm not sure that it's a good idea to implement what you proposed. The main idea of `setup-{tool}` action (`setup-mint` in this case) is to provide a **stable** tool for users too be used in their pipeline. And I have too many concerns that stops me of implementing it in case we provide a support of building this tool on top of custom branch:

- codebase state in branches are not considered as "stable" (even if it's master/main), so that means that its build process might be broken, it might have security issues or critical bugs.
- building this tool in GHA will depend on internal build process of that tool, so if they change it then I have to dive deep to the changes in order to do the same in GHA which is pain in the ass TBH.

Generally I don't see any problems with supporting non-stable versions (pre-release or alpha) but anyway they still have to be published by tool owner as pre-release but we shouldn't build it "manually".

As an examples, if you take a look at `setup-go`, `setup-node`, etc. then you will see that none of them have support of building the tool based on branches for a good reasons IMO.

**Comment by bbugh** [comment]
Ah! Good point. That's what I was hoping to avoid, but you're right it would put too much on here. Thanks for the reply. I'll find a way to do it with the `mintlang/mint:latest` docker image.
